spring.application.name=gradeflow
# Server
server.port=${PORT:8080}

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/gradeflow
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
JWT_SECRET=392ccd94fdfe7490c214fd7868898854fb765d53631fb265d79d8a89292c2cec
JWT_EXPIRATION_MS=86400000

# Default Admin Account
ADMIN_USERNAME=itadmin
ADMIN_PASSWORD=itadmin123

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

